INSERT INTO USER(ID, USER_ID, PASSWORD, NAME, EMAIL) VALUES (1, 'aaa', 'aaa', 'aaa', 'a@a');
INSERT INTO USER(ID, USER_ID, PASSWORD, NAME, EMAIL) VALUES (2, 'bbb', 'bbb', 'bbb', 'b@b');

INSERT INTO QUESTION(ID, WRITER_ID, TITLE, CONTENTS, CREATE_DATE) VALUES (1, 1, 'ababab', 'ababababababababababab', CURRENT_TIMESTAMP());
INSERT INTO QUESTION(ID, WRITER_ID, TITLE, CONTENTS, CREATE_DATE) VALUES (2, 2, 'ccccccc', 'cccccccccccccccccccccccc', CURRENT_TIMESTAMP());